use funktion
Nicklason/worldofzuul pull request #60
Opened 2019-12-03 13:53 UTC by niklas2801

Millard og jeg(Niklas) har lavet use funktion i controller scriptet.

Co-Authored-By: millardbz <millardbz@users.noreply.github.com>

2019-12-03 13:55 UTC, Nicklason requested changes

2019-12-03 13:55 UTC, Nicklason commented on src/main/java/com/mycompany/worldofzuul/RoomController.java
> +        playerInventoryListView.setItems(playerItems);
Ad

2019-12-03 13:57 UTC, Nicklason approved these changes

2019-12-04 08:43 UTC, MargaritaMariaHansen approved these changes

2019-12-04 08:44 UTC, merged