har lavet end screen
Nicklason/worldofzuul pull request #80
Opened 2019-12-09 21:01 UTC by niklas2801

#62 har tilføjet end screen

2019-12-09 21:55 UTC, Nicklason requested changes

2019-12-09 21:55 UTC, Nicklason commented on src/main/java/com/mycompany/worldofzuul/App.java
> +        scene = new Scene(loadFXML("rooms/lake"));
Burde ikke ændres

2019-12-09 21:55 UTC, Nicklason commented on src/main/java/com/mycompany/worldofzuul/Game.java
> +                if (count >= (maxcount / 100) * 66) {
Burde være count / maxcount >= 2/3 eller 0.66

2019-12-09 21:55 UTC, Nicklason commented on src/main/java/com/mycompany/worldofzuul/Game.java
> +            }
Kan man ikke bare lave et loop som tjekker for hvert rum i stedet for alle de if-statements?

2019-12-10 11:50 UTC, Nicklason approved these changes

2019-12-10 11:56 UTC, nico8034 approved these changes

2019-12-10 11:56 UTC, trundlebob approved these changes
:)

2019-12-10 11:56 UTC, merged